### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by bdehondt** [sidoh/esp8266_thermometer#2]
Hello,
I really look to use this code on my ESP8266 development board.
After some hours trial and error, I do not manae to compile the code.
When I look in the compiler debug output some includes are missing and cannot find them : 
#include <ThermometerWebserver.h>

#include <HmacHelpers.h>
#include <Settings.h>
#include <IntParsing.h>
#include <TempIface.h>
#include <MqttClient.h>

Any help ?

Many thanks

**Comment by sidoh** [comment]
Hiya @bdehondt, how are you compiling it?  Couple of tips --

* Try one of the [pre-compiled binaries](https://github.com/sidoh/esp8266_thermometer/releases).  You can flash these with `esptool.py` or something similar.
* If you do want to compile it yourself, use PlatformIO:
  ```
   platformio run -e nodemcuv2 --target upload
  ```

**Comment by bdehondt** [comment]
Hello Chris,

 

I tried to compile using Arduino IDE.

Now I installed platformIO but this is too complicated.

 

I downloaded the precompliled libraries and uploaded to the ESP8266 and now this works

 

Many thanks,

Bart

 

Van: Chris Mullins <notifications@github.com> 
Verzonden: zondag 5 april 2020 22:19
Aan: sidoh/esp8266_thermometer <esp8266_thermometer@noreply.github.com>
CC: bdehondt <bart.dehondt@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [sidoh/esp8266_thermometer] Can not compile (#2)

 

Hiya @bdehondt <https://github.com/bdehondt> , how are you compiling it? Couple of tips --

*	Try one of the pre-compiled binaries <https://github.com/sidoh/esp8266_thermometer/releases> . You can flash these with esptool.py or something similar.
*	If you do want to compile it yourself, use PlatformIO: 

*         platformio run -e nodemcuv2 --target upload
